name: Create Branch If Not Exists

on:
  push:
    branches:
      - main

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if branch exists
        id: check_branch
        run: |
          branch_name="builds"
          if git show-ref --verify --quiet "refs/heads/$branch_name"; then
            echo "::set-output name=branch_exists::true"
          else
            echo "::set-output name=branch_exists::false"
          fi

      - name: Create branch if not exists
        if: steps.check_branch.outputs.branch_exists == 'false'
        run: |
          branch_name="builds"
          git checkout --orphan $branch_name
          git rm -rf .
          touch .gitkeep
          git add .
          git commit -m "Initial commit for new branch"
          git push origin $branch_name
