name: Create Branch If Not Exists

on:
  push:
    branches:
      - main

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set pull configuration
        run: |
          git config --global pull.rebase false  # Merge divergent branches

      - name: Check if branch exists
        id: check_branch
        run: |
          branch_name="builds"
          if git show-ref --verify --quiet "refs/heads/$branch_name"; then
            echo "::set-output name=branch_exists::true"
          else
            echo "::set-output name=branch_exists::false"
          fi

      - name: Create branch if not exists
        run: |
          branch_name="builds"
          if ${{steps.check_branch.outputs.branch_exists == 'true'}}; then
            echo ""
          else
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git checkout --orphan $branch_name || exit 0  # Exit successfully if branch already exists
            git rm -rf .
            echo '{' >> repo.json
            echo '  "name": "cloudstream repository",' >> repo.json
            echo '  "description": "description",' >> repo.json
            echo '  "manifestVersion": 1,' >> repo.json
            echo '  "pluginLists": [' >> repo.json
            echo '    "https://raw.githubusercontent.com/user/repo/builds/plugins.json"' >> repo.json
            echo '  ]' >> repo.json
            echo '}' >> repo.json
            echo '## Edit file repo.json' >> README.md
            echo '- name' >> README.md
            echo '- description' >> README.md
            echo '- user/repo' >> README.md
            git add README.md repo.json
            git commit -m "Initial commit for new branch"
            git pull origin $branch_name --allow-unrelated-histories  # Pull changes from remote branch
            git push origin $branch_name
          fi
